### PR TITLE
Light-weight CPP wrapper for IntelGalileo, Grove Starter Kit sensors and minor fixes

### PR DESCRIPTION
**Pull request by ivanignatiev**
There are few propositions to use:
* light-weight cpp wrapper of a sender based on qpid-proton 0.8 (libraries included and I know that there is official cpp api but it has dependencies on boost, etc.) - maybe it'll inspire somebody 
* classes for Temperature and Light sensors of the Seed Grove Starter kit (an analogy of Intel iot-devkit)
* some minor fixes and ideas: most of code is in C++ now (include a time and encoding conversions), path to the configuration file wasn't relative (ReadConfiguration() in setup()) and there was credentials (maybe real) in the config file (ConnectTheDotsGalileo.exe.config)

I've tested on Intel Galileo Gen2 with Seeed Grove Starter Kit Plus and the last available Windows for IoT build.

### CODE REVIEW

**Comment by ivanignatiev** [comment]
Also I've added the commit with the little guide and scripts for qpid-proton 0.8 and openssl 1.0.2beta3 building under Windows 8.1 for the last build of Windows for IoT.
https://github.com/ivanignatiev/connectthedots/commit/400326c5386506d0933ebbbaaf52c2fe560f2010

**Comment by toolboc** [comment]
@ivanignatiev, great additions!  However, I am encountering a number of issues with this PR. 

Tested against the latest version of Windows for IoT: 
9600.16384.x86fre.winblue_rtm_iotbuild.141114-1440_galileo_v2.wim
11/21 – WindowsDeveloperProgramforIoT.msi

**1.**  The code requires modification in order to successfully build and deploy as-is:**

Assuming the user has configured their device according to http://ms-iot.github.io/content/SetupGalileo.htm 

Requires modifying the following values in:
(Project Properties => Configuration Properties => Debugging) 

*Remote Command: c:\test\$(TargetFileName)
Working Directory: c:\test
Remote Server Name: mygalileo
Deployment Directory: c:\test
Additional Files to Deploy: $(ProjectDir)\ConnectTheDotsGalileo.exe.config;$(SolutionDir)\lib\ssleay32.dll;$(SolutionDir)\lib\libeay32.dll;$(SolutionDir)\lib\qpid-proton.dll;*

**2.**  Using the already included qpid-proton-0.6 dlls with this code results in message not successfully  sending to Azure.  

Specifically, *unable to connect to amqps://D1:MYKEY@ConnectsTheDotsDX-ns.servicebus.windows.net:5671/ehdevices: getaddrinfo(ConnectsTheDotsDX-ns.servicebus.windows.net, 5671): No such host is known.*

Perhaps this is due to configuration changes in ConnectTheDotsGalileo.exe.config?  Key, KeyName, Namepace, and EventHubName removed and Host, Path, User, Password added. 
See: https://github.com/MSOpenTech/connectthedots/blob/master/Devices/IntelGalileo/ConnectTheDotsGalileo/ConnectTheDotsGalileo.exe.config

Furthermore, the previous changeset included diagnostic output which is now missing.  Example:

ScreenShot

Although not necessary for functionality, this is very useful in detecting issues in user configuration. 

**3.**  Using the dlls produced by the included build scripts in this changeset produce an "Entry Point Not Found" error when copied to /lib/ for inclusion in device deployment.  I recall having issues using the qpid-proton-0.8 on the Galileo during development of the initial Galileo support which resulted in choosing qpid-proton-0.6.  

ScreenShot

**Comment by ivanignatiev** [comment]
@toolboc, thank you for the detailed description of issues!

1. Sorry, I've skipped user configuration because of the *.user rule in `.gitignore` (the same issue with currently accepted project in the repo)

2. I've put back tracking features and added `Log()` instead of `printf()`, to be able to see messages in Output of Visual Studio. Sorry, I have skipped it before.  Play with `TRACKMESSAGES` definition in `Main.cpp` to enable/disable tracking.  
 
3. I removed include/ and lib/ directories and add c:\Sources to configuration of the project to avoid .lib/.dll/.h versions ambiguity. I am using the same build of Windows and tools without any customization, and my remote debugging works well: 
remoterunning

That works for me with openssl 1.0.2beta3 and qpid-proton 0.8 built by my `*-release.bat` scripts. I am playing with Intel Galileo **Gen2**, maybe there is an issue? I hope there is possibility to launch the last version of qpid-proton. 

Maybe scripts throw some errors during execution and you've get a wrong build? (or maybe there is needs to run as administrator because we're working on C: drive) Could you please try to execute command by command manually to detect errors?

**Comment by toolboc** [comment]
@ivanignatiev, thanks for the detailed reply!

1.  We should consider breaking the *.user rule for this project, as it would be ideal to have a user modify the ConnectTheDotsGalileo.exe.config, build, deploy and see the project just work.  Perhaps get some weigh-in from others i.e. @olivierbloch  You are correct that this was an issue prior to your PR.

2.  I love the idea of making tracking configurable and agree with using  Log()  over  printf().  

3.  I tested earlier on a Galileo **Gen1**, I have a **Gen2** on hand to test on to determine whether there is a hardware issue at play.  My builds appeared to complete successfully, but I will double-check based on your suggestions.  Regarding building from source, again, it would be ideal to have a user simply build and deploy without the need to install Git, Perl, Cmake, and Python to build qpid-proton and OpenSSL from source, so it may make sense to include prebuilt binaries.  Again, I think the opinion of others would be important here.

I will test early tomorrow and report back.  At this time, I am mainly concerned with ensuring the solution is easy for other to replicate.

**Comment by ivanignatiev** [comment]
@toolboc ,thank you!

On Galileo Gen2 you can launch application without any shield if you'll decomment `SIMULATEDATA` definition and put in comments whether shield definition. If it'll work with Gen2 I'll downgrage scripts and code to qpid-proton 0.6. But I really don't difference between Gen1 and Gen2 Windows behavior. 

With .user project files `git add -f` command works well, so it'll force developers to verify what they're commiting (to remove private data, etc.). I think it's fine with .gitignore like it is, but one good thing to add some instruction about it in contribution guide. 

About binaries: I wonder to make nuget package for qpid-proton with openssl for Windows IoT and just add it to packages.config. When I'll get a feedback from you about versions I'll try to make it with coapp help.

**Comment by toolboc** [comment]
@ivanignatiev, default configuration looks good, also great idea making `TRACKMESSAGES` configurable.  That said, I am still getting "Entry Point Not Found" on my **Gen1** device running latest Window for IoT image. I went to test on my **Gen2** but it appears my device is dead, so I am unable to test at this time.  There very well may be a hardware inconsistency.  Provided we can resolve this, I agree with the idea of distributing working binaries via coapp.

**Comment by ivanignatiev** [comment]
Here it is, qpid-proton 0.6 and unofficial nuget package. 
I've published it from my account just to test that it works well ( https://www.nuget.org/packages/qpidprotoniot/ ).

**Comment by toolboc** [comment]
@ivanignatiev, latest PR works great running on Windows 10 Preview build 9926 against 9600.16384.x86fre.winblue_rtm_iotbuild.141114-1440_galileo_v2.wim running on Intel Galileo **Gen1**.  It appears that the build scripts create an unusable output when built on Win10 at this time. Given this news, I am willing to bet qpid-proton-0.8 will work but needs to be built on a stable OS (i.e. Win8.1).  Great job!

**Comment by ivanignatiev** [comment]
@toolboc thank you for the excellent feedback! I've published NuGet package for qpid-proton 0.8 https://www.nuget.org/packages/Apache.Qpid.Proton.Unoff.IA32/ and commit changes in the project. It should work well now.

**Comment by toolboc** [comment]
@ivanignatiev, 0.8 binaries working great!  Excellent work!

**Comment by olivierbloch** [comment]
Hy guys. Sorry I am only now looking into this (had some fire drills to take care off over the last few days). I will test this on my Gen 1 tomorrow and let you know if I have issues. If not, this PR should be merged tomorrow.
Thanks for your help on the project!

**Pull request merged**
